### ISSUE TITLE
Publishes to every client.

### ISSUE THREAD

**Issue by PritamUpadhyay** [BrainCrumbz/mosca-publish-demo#1]
That code, you given in server.js, publishes to every client connected to mosca server.
Can I publish to particular client (or to only those clients which are on that specific topic) ?
Thanks,
Pritam Upadhyay.

**Comment by BrainCrumbz** [comment]
Hello
please consider that this is just a demo created to show an issue that we had while working on mosca, so it's now a full blown demo or tutorial of sort.

Anyway: as far as I rememer, clients can normally _subscribe_ to some channel, as well as clients (and server too) can normally _publish_ onto some channel. So what you're asking for should be regular activity. Have you tried already looking at official mosca docs?

**Comment by PritamUpadhyay** [comment]
I have asked author about this issue and he told me that this is the normal behaviour of library. if you use server.publish() [in your case it is broker.publish()], it will by default send message to all client.

Btw, Have you found any workaround for this issue? 

Thanks,
Pritam Upadhyay.

**Comment by BrainCrumbz** [comment]
one thing at a time :)
1. yes, with mosca (and I think with MQTT in general) you can normally select _what_ to listen to (subscribe) as well as _where_ to publish to. Have a look e.g. at [these slides](http://mcollina.github.io/mqtt_and_nodejs) from mosca author. In particular, look at [slide 9](http://mcollina.github.io/mqtt_and_nodejs/#9) and [10](http://mcollina.github.io/mqtt_and_nodejs/#10). There you can see as channels are identified by a sort of _tree_ of topics, so e.g. you can publish to `"clients/client1"`, `"clients/client2"`, and subscribe to `"clients/+"` to listem to all of them.
2. yes and no. We were able to publish messages directly from the server if that was backed by in-memory persistence. When we tried the same thing with server backed by a remote mongoDB server persistence, we faced the issue mentioned here. Our remote mongoDb persistence setup seems to be correct. We did not investigated yet in the root cause. Maybe we will try changing server in a future test.

**Comment by PritamUpadhyay** [comment]
Please let me know if you find anything regarding this.

Thanks,
Pritam Upadhyay

**Comment by BrainCrumbz** [comment]
In case, we can update this thread, or the one on mosca github project. Anyway, in order to setup a mongoDb-based persistence, start from official wiki references, trying to ignore what we setup here (just in case we drive you on the wrong way).

Cheers
